server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: cloud-alibaba
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 10.0.0.59:9876
  producer:
    group: cloud-alibaba-group
