

### 1
GET http://{{ server }}/

### 自定义限流规则 testRule
GET http://{{ server }}/testRule

### 自定义限流规则 testRule2
GET http://{{ server }}/testRule2

### apOne回显 /echo/{str}
GET http://{{ server }}/echo/111

### apOne请求apTwo /echoFromTwo/{str}
GET http://{{ server }}/echoFromTwo/who
